spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 237a25e848fdc6518643
            client-secret: 053e78c63be4fec00ea2df9ea9c663805abfea9d

logging:
  level:
    fr.alexandreroman.chatboxx: DEBUG
