management:
  endpoints:
    web:
      exposure:
        include: health

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: chatboxx-messages
        input:
          destination: chatboxx-messages
  mvc:
    favicon:
      enabled: false
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: fbd25a3941cb7f7d4a40
            client-secret: aa93dff4b3bb3c1eed0d1dcba751d1458e1c1909

server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: false
