---
apiVersion: v1
kind: Service
metadata:
  name: app-lb
  namespace: chatboxx
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    role: app
