---
kind: ConfigMap
apiVersion: v1
metadata:
  name: app
  namespace: chatboxx
data:
  application.yml: |-
    spring:
      cloud:
        gcp:
          credentials:
            location: file:/gcp/credentials.json

# You need to set Google Credentials in a ConfigMap object:
# $ kubectl -n chatboxx create configmap gcp-config --from-file=credentials.json=my-credentials.json
