---
kind: ConfigMap
apiVersion: v1
metadata:
  name: app
  namespace: chatboxx
data:
  application.yml: |-
    spring:
      cloud:
        gcp:
          credentials:
            location: file:/gcp/chatboxx-gcp-credentials.json

# You need to set Google credentials in order to use GCP services.

# Enable Google Pub/Sub on your GCP account:
# $ gcloud services enable pubsub.googleapis.com

# Create a GCP service account for Pub/Sub:
# $ gcloud iam service-accounts create chatboxx --display-name "Chatboxx"
# $ export PROJECT_ID=$(gcloud config get-value project)
# $ gcloud projects add-iam-policy-binding ${PROJECT_ID} --member "serviceAccount:chatboxx@${PROJECT_ID}.iam.gserviceaccount.com" --role "roles/pubsub.editor"

# Create a service key for this account:
# $ gcloud iam service-accounts keys create chatboxx-gcp-credentials.json --iam-account chatboxx@${PROJECT_ID}.iam.gserviceaccount.com

# Create a K8s secret with GCP credentials:
# $ kubectl -n chatboxx create secret generic gcp-credentials --from-file chatboxx-gcp-credentials.json
